# Generated by Django 4.1.7 on 2023-03-19 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_penilaian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataabsensisiswa',
            name='catatatn',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 19, 47, 629532)),
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 19, 47, 629532)),
        ),
    ]
