# Generated by Django 4.1.7 on 2023-03-19 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_guru', '0012_alter_dataguru_created_alter_dataguru_updated_and_more'),
        ('api_staf', '0015_alter_datakelas_created_alter_datakelas_updated_and_more'),
        ('api_penilaian', '0002_dataabsensisiswa_catatatn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataabsensisiswa',
            old_name='catatatn',
            new_name='catatan',
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 29, 4, 915266)),
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 29, 4, 915266)),
        ),
        migrations.CreateModel(
            name='DataNilaiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('Latihan', 'Latihan'), ('Pekerjaan Rumah', 'PR'), ('Ulangan Semester I', 'Ulangan Semester I'), ('Ulangan Semester II', 'Ulangan Semester II'), ('Ujian Semester I', 'Ujian Semester I'), ('Ujian Semester II', 'Ujian Semester II')], max_length=30)),
                ('nilai', models.FloatField(default=0.0)),
                ('catatan', models.TextField(blank=True, max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 29, 4, 916264))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 29, 4, 916264))),
                ('id_abs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_penilaian.dataabsensisiswa', verbose_name='Absensi siswa')),
                ('kd_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_staf.datakelas', verbose_name='Pilih Kelas')),
                ('kd_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_guru.mapelguru')),
            ],
            options={
                'verbose_name_plural': 'Penilaian Siswa',
            },
        ),
    ]
