# Generated by Django 4.1.7 on 2023-03-19 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_penilaian', '0003_rename_catatatn_dataabsensisiswa_catatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datanilaisiswa',
            name='kd_kelas',
        ),
        migrations.RemoveField(
            model_name='datanilaisiswa',
            name='kd_mapel',
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 34, 24, 936216)),
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 34, 24, 936216)),
        ),
        migrations.AlterField(
            model_name='datanilaisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 34, 24, 936216)),
        ),
        migrations.AlterField(
            model_name='datanilaisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 34, 24, 936216)),
        ),
    ]
