# Generated by Django 4.1.7 on 2023-03-20 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_penilaian', '0007_alter_dataabsensisiswa_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 0, 5, 341608)),
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 0, 5, 341608)),
        ),
        migrations.AlterField(
            model_name='datanilaisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 0, 5, 342608)),
        ),
        migrations.AlterField(
            model_name='datanilaisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 0, 5, 342608)),
        ),
    ]
