# Generated by Django 4.1.7 on 2023-03-20 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_penilaian', '0010_alter_dataabsensisiswa_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 387800)),
        ),
        migrations.AlterField(
            model_name='dataabsensisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 387800)),
        ),
        migrations.AlterField(
            model_name='datanilaisiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 388800)),
        ),
        migrations.AlterField(
            model_name='datanilaisiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 388800)),
        ),
    ]
