# Generated by Django 4.1.7 on 2023-03-20 00:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_siswa', '0014_alter_datasiswa_created_alter_datasiswa_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml_bayar', models.CharField(default='-', max_length=30)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], max_length=15)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 46, 38, 415462))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 46, 38, 415462))),
                ('kd_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_siswa.datasiswa', to_field='nis_siswa')),
            ],
            options={
                'verbose_name_plural': 'Pembayaran Siswa',
            },
        ),
    ]
