# Generated by Django 4.1.7 on 2023-03-20 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0021_alter_datakelas_created_alter_datakelas_updated_and_more'),
        ('api_akutansi', '0002_alter_datapembayaran_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapembayaran',
            name='jenis_pby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_staf.datakeuangan'),
        ),
        migrations.AlterField(
            model_name='datapembayaran',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 0, 58, 446169)),
        ),
        migrations.AlterField(
            model_name='datapembayaran',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 0, 58, 446169)),
        ),
    ]
