# Generated by Django 4.1.7 on 2023-03-20 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0024_datagaji_alter_databerita_created_and_more'),
        ('api_akutansi', '0005_alter_datapembayaran_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapembayaran',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 650580)),
        ),
        migrations.AlterField(
            model_name='datapembayaran',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 650580)),
        ),
        migrations.CreateModel(
            name='GajiStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml_bayar', models.CharField(default='-', max_length=30)),
                ('status', models.CharField(choices=[('Sudah Dibayar', 'Sudah Dibayar'), ('Tertunda', 'Tertunda')], max_length=15)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 650580))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 650580))),
                ('id_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_staf.datastaff', to_field='kd_staf')),
            ],
            options={
                'verbose_name_plural': 'Gaji Staff',
            },
        ),
    ]
