# Generated by Django 4.1.7 on 2023-03-20 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_akutansi', '0006_alter_datapembayaran_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapembayaran',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 42, 13, 562700)),
        ),
        migrations.AlterField(
            model_name='datapembayaran',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 42, 13, 562700)),
        ),
        migrations.AlterField(
            model_name='gajistaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 42, 13, 562700)),
        ),
        migrations.AlterField(
            model_name='gajistaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 42, 13, 562700)),
        ),
    ]
