# Generated by Django 4.1.7 on 2023-03-20 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_guru', '0023_alter_dataguru_created_alter_dataguru_updated_and_more'),
        ('api_akutansi', '0007_alter_datapembayaran_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapembayaran',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 357112)),
        ),
        migrations.AlterField(
            model_name='datapembayaran',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 357112)),
        ),
        migrations.AlterField(
            model_name='gajistaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 358112)),
        ),
        migrations.AlterField(
            model_name='gajistaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 358112)),
        ),
        migrations.CreateModel(
            name='GajiGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml_bayar', models.CharField(default='-', max_length=30)),
                ('status', models.CharField(choices=[('Sudah Dibayar', 'Sudah Dibayar'), ('Tertunda', 'Tertunda')], max_length=15)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 359113))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 359113))),
                ('id_guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_guru.dataguru', to_field='kd_guru')),
            ],
            options={
                'verbose_name_plural': 'Gaji Guru',
            },
        ),
    ]
