# Generated by Django 4.1.7 on 2023-03-18 03:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_staf', '0004_alter_datamapel_created_alter_datamapel_kd_mapel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_guru', models.CharField(max_length=13, unique=True)),
                ('nm_guru', models.CharField(max_length=100)),
                ('jbt_guru', models.CharField(choices=[('Guru Mapel', 'Guru Mata Pelajaran'), ('Guru Kelas', 'Guru Kelas'), ('Guru Pendidikan Agama', 'Guru Pendidikan Agama')], max_length=100)),
                ('jen_kel', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=12)),
                ('thn_aktif', models.DateField(default='2023-03-18')),
                ('thn_nonaktif', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 10, 52, 29, 990839))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 10, 52, 29, 990839))),
            ],
            options={
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='Mapel_Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 10, 52, 29, 991837))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 10, 52, 29, 991837))),
                ('id_guru', models.ForeignKey(db_column='kd_guru', on_delete=django.db.models.deletion.CASCADE, to='api_guru.dataguru', to_field='kd_guru')),
                ('id_mapel', models.ForeignKey(db_column='kd_mapel', on_delete=django.db.models.deletion.CASCADE, to='api_staf.datamapel', to_field='kd_mapel')),
            ],
            options={
                'verbose_name_plural': 'Mapel Guru',
            },
        ),
    ]
