# Generated by Django 4.1.7 on 2023-03-18 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guru', '0002_mapelguru_alter_dataguru_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataguru',
            name='alamat',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dataguru',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataguru',
            name='no_hp',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 24, 57, 214606)),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 24, 57, 214606)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 24, 57, 215606)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 24, 57, 215606)),
        ),
    ]
