# Generated by Django 4.1.7 on 2023-03-18 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_guru', '0003_dataguru_alamat_dataguru_email_dataguru_no_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_mapel', models.CharField(max_length=13, unique=True)),
                ('nm_mapel', models.CharField(max_length=100)),
                ('kkm_mapel', models.FloatField(default=7.0, max_length=3)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 430026))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 430026))),
            ],
            options={
                'verbose_name_plural': 'Mapel',
            },
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 429026)),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 429026)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 430026)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 430026)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='id_mapel',
            field=models.ForeignKey(db_column='kd_mapel', on_delete=django.db.models.deletion.CASCADE, to='api_guru.datamapel', to_field='kd_mapel'),
        ),
    ]
