# Generated by Django 4.1.7 on 2023-03-20 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guru', '0013_alter_dataguru_created_alter_dataguru_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 2172)),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='thn_aktif',
            field=models.DateField(default='2023-03-20'),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 2172)),
        ),
        migrations.AlterField(
            model_name='datamapel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 3172)),
        ),
        migrations.AlterField(
            model_name='datamapel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 3172)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 3172)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 3172)),
        ),
    ]
