# Generated by Django 4.1.7 on 2023-03-20 01:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_siswa', '0018_alter_datasiswa_created_alter_datasiswa_updated'),
        ('api_guru', '0019_alter_dataguru_created_alter_dataguru_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 381803)),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='jbt_guru',
            field=models.CharField(choices=[('Guru Mapel', 'Guru Mata Pelajaran'), ('Guru Kelas', 'Guru Kelas'), ('Guru Pendidikan Agama', 'Guru Pendidikan Agama'), ('Guru Konseling', 'Guru Konseling')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 381803)),
        ),
        migrations.AlterField(
            model_name='datamapel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 382803)),
        ),
        migrations.AlterField(
            model_name='datamapel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 382803)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 382803)),
        ),
        migrations.AlterField(
            model_name='mapelguru',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 382803)),
        ),
        migrations.CreateModel(
            name='DataKonseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField()),
                ('status', models.CharField(choices=[('Selesai', 'Lanjutan')], max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 383802))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 38, 13, 383802))),
                ('kd_guru', models.ForeignKey(db_column='kd_guru', on_delete=django.db.models.deletion.CASCADE, to='api_guru.dataguru', to_field='kd_guru')),
                ('kd_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_siswa.datasiswa', to_field='nis_siswa')),
            ],
            options={
                'verbose_name_plural': 'Konseling',
            },
        ),
    ]
