# Generated by Django 4.1.7 on 2023-03-18 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasiswa',
            options={'verbose_name_plural': 'Siswa'},
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 425029)),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 426028)),
        ),
    ]
