# Generated by Django 4.1.7 on 2023-03-18 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_siswa', '0002_alter_datasiswa_options_alter_datasiswa_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 16, 3, 44, 565676)),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 16, 3, 44, 565676)),
        ),
    ]
