# Generated by Django 4.1.7 on 2023-03-18 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_guru', '0008_alter_dataguru_created_alter_dataguru_thn_aktif_and_more'),
        ('api_siswa', '0005_alter_datasiswa_created_alter_datasiswa_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 915868)),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='thn_masuk',
            field=models.DateField(default='2023-03-19'),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 915868)),
        ),
        migrations.CreateModel(
            name='DataNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_siswa', models.FloatField(default=0.0, max_length=3)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 916866))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 916866))),
                ('id_mapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_guru.mapelguru')),
                ('id_siswa', models.ForeignKey(blank=True, db_column='nis_siswa', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_siswa.datasiswa', to_field='nis_siswa')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
    ]
