# Generated by Django 4.1.7 on 2023-03-19 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_siswa', '0009_alter_datasiswa_created_alter_datasiswa_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 29, 4, 897278)),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 29, 4, 897278)),
        ),
    ]
