# Generated by Django 4.1.7 on 2023-03-20 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_siswa', '0011_alter_datasiswa_created_alter_datasiswa_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasiswa',
            name='status_pby',
            field=models.CharField(blank=True, choices=[('Reguler', 'Reguler'), ('Beasiswa', 'Beasiswa')], max_length=15),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 27, 999175)),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='thn_masuk',
            field=models.DateField(default='2023-03-20'),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 27, 999175)),
        ),
    ]
