# Generated by Django 4.1.7 on 2023-03-20 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_siswa', '0012_datasiswa_status_pby_alter_datasiswa_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 455994)),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 455994)),
        ),
    ]
