# Generated by Django 4.1.7 on 2023-03-18 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_mapel', models.CharField(max_length=13)),
                ('nm_mapel', models.CharField(max_length=100)),
                ('kkm_mapel', models.FloatField(default=7.0, max_length=3)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 7, 54, 54, 46901))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 7, 54, 54, 46901))),
            ],
        ),
        migrations.CreateModel(
            name='DataStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_staf', models.CharField(max_length=13)),
                ('nm_staff', models.CharField(max_length=100)),
                ('jen_kel', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=12)),
                ('thn_aktif', models.DateField(default='2023-03-18')),
                ('thn_nonaktif', models.DateField(default='Masih Aktif')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 7, 54, 54, 45901))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 7, 54, 54, 45901))),
            ],
        ),
    ]
