# Generated by Django 4.1.7 on 2023-03-18 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0002_alter_datamapel_options_alter_datastaff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamapel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 8, 6, 38, 53400)),
        ),
        migrations.AlterField(
            model_name='datamapel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 8, 6, 38, 53400)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 8, 6, 38, 52400)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='thn_nonaktif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 8, 6, 38, 52400)),
        ),
    ]
