# Generated by Django 4.1.7 on 2023-03-18 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0004_alter_datamapel_created_alter_datamapel_kd_mapel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamapel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 11, 7, 38, 386503)),
        ),
        migrations.AlterField(
            model_name='datamapel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 11, 7, 38, 386503)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 11, 7, 38, 386503)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 11, 7, 38, 386503)),
        ),
    ]
