# Generated by Django 4.1.7 on 2023-03-18 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guru', '0004_datamapel_alter_dataguru_created_and_more'),
        ('api_staf', '0006_alter_datamapel_created_alter_datamapel_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_kelas', models.CharField(max_length=13, unique=True)),
                ('lama_jam', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 431025))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 431025))),
            ],
            options={
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.DeleteModel(
            name='DataMapel',
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 431025)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 15, 57, 4, 431025)),
        ),
    ]
