# Generated by Django 4.1.7 on 2023-03-18 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0008_alter_datakelas_created_alter_datakelas_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakelas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 25, 29, 859096)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='kd_kelas',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2B'), ('3A', '3B'), ('4A', '4B'), ('5A', '5B'), ('6A', '6B')], max_length=13),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 25, 29, 859096)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 25, 29, 859096)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 25, 29, 859096)),
        ),
    ]
