# Generated by Django 4.1.7 on 2023-03-18 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_siswa', '0005_alter_datasiswa_created_alter_datasiswa_updated'),
        ('api_guru', '0007_alter_dataguru_created_alter_dataguru_updated_and_more'),
        ('api_staf', '0009_alter_datakelas_created_alter_datakelas_kd_kelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakelas',
            name='id_guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_guru.dataguru', to_field='kd_guru'),
        ),
        migrations.AddField(
            model_name='datakelas',
            name='id_siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_siswa.datasiswa', to_field='nis_siswa'),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 31, 15, 532155)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 31, 15, 532155)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 31, 15, 532155)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 19, 31, 15, 532155)),
        ),
    ]
