# Generated by Django 4.1.7 on 2023-03-18 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0010_datakelas_id_guru_datakelas_id_siswa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakelas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 917866)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 917866)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 916866)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='thn_aktif',
            field=models.DateField(default='2023-03-19'),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 5, 59, 48, 916866)),
        ),
    ]
