# Generated by Django 4.1.7 on 2023-03-20 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0016_alter_datakelas_created_alter_datakelas_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Reguler', 'Reguler'), ('Beasiswa', 'Beasiswa')], max_length=100)),
                ('biaya', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 4171))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 4171))),
            ],
            options={
                'verbose_name_plural': 'Keuangan',
            },
        ),
        migrations.AddField(
            model_name='datastaff',
            name='role_staf',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Keuangan', 'Keuangan'), ('Tata Usaha', 'Tata Usaha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 4171)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 4171)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 4171)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='thn_aktif',
            field=models.DateField(default='2023-03-20'),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 42, 28, 4171)),
        ),
    ]
