# Generated by Django 4.1.7 on 2023-03-20 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0017_datakeuangan_datastaff_role_staf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakelas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 460992)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 460992)),
        ),
        migrations.AlterField(
            model_name='datakeuangan',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 461991)),
        ),
        migrations.AlterField(
            model_name='datakeuangan',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 461991)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 460992)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 7, 44, 13, 460992)),
        ),
    ]
