# Generated by Django 4.1.7 on 2023-03-20 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0023_alter_databerita_created_alter_databerita_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_role', models.CharField(choices=[('Staff', 'Staff'), ('Guru', 'Guru')], max_length=15)),
                ('gaji', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 644797))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 644797))),
            ],
            options={
                'verbose_name_plural': 'Gaji',
            },
        ),
        migrations.AlterField(
            model_name='databerita',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 644797)),
        ),
        migrations.AlterField(
            model_name='databerita',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 644797)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 643798)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 643798)),
        ),
        migrations.AlterField(
            model_name='datakeuangan',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 643798)),
        ),
        migrations.AlterField(
            model_name='datakeuangan',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 643798)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 642799)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 40, 24, 642799)),
        ),
    ]
