# Generated by Django 4.1.7 on 2023-03-20 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_staf', '0025_alter_databerita_created_alter_databerita_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databerita',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 342122)),
        ),
        migrations.AlterField(
            model_name='databerita',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 342122)),
        ),
        migrations.AlterField(
            model_name='datagaji',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 342122)),
        ),
        migrations.AlterField(
            model_name='datagaji',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 342122)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 341123)),
        ),
        migrations.AlterField(
            model_name='datakelas',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 341123)),
        ),
        migrations.AlterField(
            model_name='datakeuangan',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 341123)),
        ),
        migrations.AlterField(
            model_name='datakeuangan',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 341123)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 340123)),
        ),
        migrations.AlterField(
            model_name='datastaff',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 50, 32, 340123)),
        ),
    ]
